//Try Catch

try{

    let a = 2 + b;
}catch(erro){
    console.log(erro);
}


console.log("teste");